packages:
  - '.'
supportedArchitectures:
  os:
    - linux
  cpu:
    - x64
    - arm64
  libc:
    - glibc
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - 'esbuild'
allowBuilds:
  '@tailwindcss/oxide': set this to true or false
  esbuild: set this to true or false
